### ISSUE TITLE
Defining schemas within a response object

### ISSUE THREAD

**Issue by MatMoore** [zxchris/swaggerly#12]
This is a follow up to #7 which was a broader question about resource pages. Since then I've created a few branches to experiment with different schemas.

https://github.com/MatMoore/swaggerly/commit/02212d55a499700e3e342a8cfaf24bb55d59e3ac is a simplified version of my spec.

I've been using https://github.com/swagger-api/swagger-node to validate.

With this example, my Response page describes the document field as `array[array]`. I compared this to the examples discussed in #11, and the only obvious difference is that in this schema I describe my schema inline in a response, e.g.
```
      "responses": {
 +          "200": {
 +            "description": "Results of the search",
 +            "schema": {
 +              "title": "Search response",
 +              "properties": {
```

rather than using a `ref` to a model defined elsewhere. Is there any reason why this wouldn't be valid?

A related problem I noticed is trying to add a non-object response. For example, the swagger pet store example has a login request that returns a plain string. Swagger-ui presents this as "Response Class (Status 200) string": http://petstore.swagger.io/#!/user/loginUser

Unfortunately I don't seem to be able to do the same thing in swaggerly. I committed an example here https://github.com/MatMoore/swaggerly/commits/simple-response-example - this basically expands the string field into its own resource, which would be quite confusing for a non-json content type.

**Comment by zxchris** [comment]
Defining a model inline with the response declaration should be valid, not just through a $ref. go-swagger, the underlying spec parser, must be exposing the model differently in your example case. I will investigate.

Non-object responses have just been overlooked.

Both these failing scenarios are in the same "area"....
