### ISSUE TITLE
It's unclear if tags are mandatory (they seem to be)

### ISSUE THREAD

**Issue by davidillsley** [zxchris/swaggerly#3]
I've just tried using swaggerly with an existing swagger.json which didn't have any tags. The README was ambiguous to me about whether tags were required, but the result was that without tags, I wasn't getting any content.

It'd be good if the README was clearer that the use of tags is required, and if the tool spat out a warning message if no tagged paths are found.

**Comment by zxchris** [comment]
That's a bug. Tags are not mandatory.
Fixed in commit: 
https://github.com/zxchris/swaggerly/commit/e0bf135fbdb6d3a0087eb8687cf7522e28db68d6
