### ISSUE TITLE
README is unclear if the second markdown file being in the 'level2' folder is significant

### ISSUE THREAD

**Issue by davidillsley** [zxchris/swaggerly#4]
The README is unclear if the second markdown file being in the 'level2' folder is significant. There's sort of an implication that it is, but it doesn't seem to affect the display.

**Comment by zxchris** [comment]
Thanks. I'll refine the description.

**Comment by zxchris** [comment]
Fixed building of navigation where metadata is not used.
Improved README and added additional examples to illustrate navigation depth and metadata use.

https://github.com/zxchris/swaggerly/commit/03e50087bc0dae31574d0cbf65cd3487fbb8d40f
