### ISSUE TITLE
Definitions in API reference

### ISSUE THREAD

**Issue by MatMoore** [zxchris/swaggerly#7]
Hi, I've been looking at documentation tools and I really like the work you've done on swaggerly. The ability to augment an OpenAPI spec with markdown documents is great.

I was wondering what your plans are for documenting model definitions?

As an example, the current spec describes a model for Pet that is extended by Cat and Dog subtypes:

```
{
  "definitions": {
    "Pet": {
      "type": "object",
      "discriminator": "petType",
      "properties": {
        "name": {
          "type": "string"
        },
        "petType": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "petType"
      ]
    },
    "Cat": {
      "description": "A representation of a cat",
      "allOf": [
        {
          "$ref": "#/definitions/Pet"
        },
        {
          "type": "object",
          "properties": {
            "huntingSkill": {
              "type": "string",
              "description": "The measured skill for hunting",
              "default": "lazy",
              "enum": [
                "clueless",
                "lazy",
                "adventurous",
                "aggressive"
              ]
            }
          },
          "required": [
            "huntingSkill"
          ]
        }
      ]
    },
    "Dog": {
      "description": "A representation of a dog",
      "allOf": [
        {
          "$ref": "#/definitions/Pet"
        },
        {
          "type": "object",
          "properties": {
            "packSize": {
              "type": "integer",
              "format": "int32",
              "description": "the size of the pack the dog is from",
              "default": 0,
              "minimum": 0
            }
          },
          "required": [
            "packSize"
          ]
        }
      ]
    }
  }
}
```

It would be great to see an example of how this could be rendered in swaggerly.

The APIs I tend to work with are quite simple in terms of operations, but have a complex data model, and models are reused by different resources. Ideally I'd like to be able to indicate whether models should be inlined with the method reference or go in a different section.

I noticed there is some support for resource descriptions in the uber example, (http://localhost:3123/resources/profile-resource?v=latest) - does this extend to collections and nested data structures? Is there a way to include it in the navigation tree?

**Comment by zxchris** [comment]
I've finished off support for `AllOf` and pushed.

What you get is a combined resource view, so Dog in your petstore example is rendered as:

```javascript
{
    "name": "string",
    "packSize": "integer",
    "petType": "string"
}
```

This is the clearest way to document the resource, as it really is what needs to be sent on the wire ;-)

I'm interested in your idea of choosing whether to inline models or not. If you have a clear way to show this in documentation, then we can take a look. We've only had our use cases to drive development of Swaggerly, and of course there are things that it will never do because they don't make sense, but community use cases are welcome!

Don't forget that the OpenAPI specifications themselves will be downloadable and usable with the rest of the swagger ecosystem, so the rationalisation of models into reusable sub-models will not be lost.

One thing to note, is that models **must** have a `title:` member. Swaggerly doesn't know what to call the resource without it. I will add this to the README.

Try out the latest commit dbffce0 with some of your models?

Leaving this issue open while we discuss.

**Comment by zxchris** [comment]
For clarity, Swaggerly will error and exit if a response model **does not** have a title member. See commit ee8b20e .

This is clearer than having Swaggerly continue to run, hiding the fact that one or more of the model resources have not been built.

**Comment by MatMoore** [comment]
Awesome, thanks! I wasn't able to get it describing my models completely yet, which may be due to a problem with my spec or something to with using arrays (the types currently show up as `array[array]`). but I'll take a closer look and let you know how I get on.

One thing I noticed just now is there's a typo in the error message: `s/memeber/member`

It's probably also useful to indicate the line number if that's easily accessible. Haven't investigated this myself as I'm still new to go.

Will have to think about how to handle navigation.

**Comment by zxchris** [comment]
OpenAPI arrays in general are complicated to handle, as they naturally parse into sometimes complex data structures. So it is entirely probable that Swaggerly doesn't consume this structure correctly. Swaggerly uses go-swagger to parse the specs into matching data structures, and then it turns those into its own display structures. 

I need more test cases. Assuming your specs validate with swagger-UI or online editors/validators, you can create some issues with failing (cut down but complete) specs that demonstrate the problem. That would be a great help!

**Comment by MatMoore** [comment]
Absolutely. I probably won't have much time to look at this this week, but can definitely contribute test cases if it's not a problem my side.
